---
- name: A playbook using apt
  hosts: planetexpress
  gather_facts: yes

  vars_files:
          - vars/vars-when.yml

  tasks:
          - name: use apt to install Steam Locomotive
            apt:
                    name: sl
                    state: present
            become: yes
            register: result
            when: ansible_distribution == "Ubuntu"

          - name: Show result
            debug:
                    var: result
                    verbosity: 1

          - name: Print out the cache_update_time
            debug:
                    msg: "The user {{ inventory_hostname }} has a cache_update_time of {{ result.cache_update_time }}"
            when: ansible_distribution == "Ubuntu"
   
          - name: Reading yml vars
            debug:
                    var: licensetypes.paytypes[0]
