---
- name: Apache server installed
  hosts: web
  gather_facts: no
  become: yes

  tasks:
          - name: latest apached version installed
            package:
                    name: apache2
                    state: latest

          - name: apache enabled and running
            service:
                    name: apache2
                    enabled: yes
                    state: started

          - name: render a template to push to our hosts
            template:
                    src: index.html.j2
                    dest: /var/www/html/index.html

          - name: bounce the service
            service:
                    name: apache2
                    enabled: yes
                    state: restarted

